name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/checkout@v4
        with:
          repository: moergo-sc/zmk
          ref: main
          path: src
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v14
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Get commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Rename file with commit hash
        run: cp combined/glove80.uf2 "glove80-${COMMIT_HASH}.uf2"
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: glove80-${{ env.COMMIT_HASH }}.uf2
          path: glove80-${{ env.COMMIT_HASH }}.uf2
          if-no-files-found: error
          compression-level: 0
